[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pykiosk"
version = "0.1.0"
description = "En modulær kiosk-app med Tkinter, pywebview og xrandr-rotasjon"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pywebview", "Pillow"]

[project.scripts]
pykiosk = "pykiosk.gui:main"
